version: 2
updates:
- package-ecosystem: nuget
  directory: "/SoundBoard/SoundBoard"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Costura.Fody
    versions:
    - 4.1.0
    - 5.0.2
    - 5.1.0
    - 5.2.0
  - dependency-name: Fody
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
